SUFFIX="prodQCD_17Sep_full"

python submitOnBatch.py --tag QCD_bEnriched_HT200to300_${SUFFIX} --input /afs/cern.ch/work/l/lcadamur/private/YR_bbbb_analysis/CMSSW_9_3_2/src/PhaseTwoAnalysis/delphesInterface/ntupler/config/filelists/filelist_QCD_bEnriched_HT200to300_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.dat    --location desy
python submitOnBatch.py --tag QCD_bEnriched_HT300to500_${SUFFIX} --input /afs/cern.ch/work/l/lcadamur/private/YR_bbbb_analysis/CMSSW_9_3_2/src/PhaseTwoAnalysis/delphesInterface/ntupler/config/filelists/filelist_QCD_bEnriched_HT300to500_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.dat    --location desy
python submitOnBatch.py --tag QCD_bEnriched_HT500to700_${SUFFIX} --input /afs/cern.ch/work/l/lcadamur/private/YR_bbbb_analysis/CMSSW_9_3_2/src/PhaseTwoAnalysis/delphesInterface/ntupler/config/filelists/filelist_QCD_bEnriched_HT500to700_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.dat    --location desy
python submitOnBatch.py --tag QCD_bEnriched_HT1500to2000_${SUFFIX} --input /afs/cern.ch/work/l/lcadamur/private/YR_bbbb_analysis/CMSSW_9_3_2/src/PhaseTwoAnalysis/delphesInterface/ntupler/config/filelists/filelist_QCD_bEnriched_HT1500to2000_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.dat  --location desy
python submitOnBatch.py --tag QCD_bEnriched_HT2000toInf_${SUFFIX} --input /afs/cern.ch/work/l/lcadamur/private/YR_bbbb_analysis/CMSSW_9_3_2/src/PhaseTwoAnalysis/delphesInterface/ntupler/config/filelists/filelist_QCD_bEnriched_HT2000toInf_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.dat   --location desy

python submitOnBatch.py --tag QCD_bEnriched_HT700to1000_${SUFFIX} --input /afs/cern.ch/work/l/lcadamur/private/YR_bbbb_analysis/CMSSW_9_3_2/src/PhaseTwoAnalysis/delphesInterface/ntupler/config/filelists/filelist_QCD_bEnriched_HT700to1000_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.dat   --location fnal
python submitOnBatch.py --tag QCD_bEnriched_HT1000to1500_${SUFFIX} --input /afs/cern.ch/work/l/lcadamur/private/YR_bbbb_analysis/CMSSW_9_3_2/src/PhaseTwoAnalysis/delphesInterface/ntupler/config/filelists/filelist_QCD_bEnriched_HT1000to1500_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.dat  --location fnal
